# Generated by Django 5.0.6 on 2024-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
