# Generated by Django 5.0.6 on 2024-05-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_confirmationcodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcodemodel',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
