# Generated by Django 5.0.6 on 2024-05-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_categorymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category_name',
            new_name='category',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.categorymodel'),
        ),
    ]
